apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml

configMapGenerator:
- name: ais-cluster-config-override
  files:
    - ais_cluster_override.json

generatorOptions:
  disableNameSuffixHash: true