apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/proxy

configMapGenerator:
- name: ci-images
  envs:
  - ../properties.env
- name: proxy-vars
  envs:
  - properties.env
- name: target-vars
  envs:
  - ../target/properties.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: ci-images
    fieldPath: data.AISNODE_IMAGE
  targets:
    - select:
        kind: StatefulSet
        name: ais-proxy
      fieldPaths:
        - spec.template.spec.containers.[name=aisnode].image
- source:
    kind: ConfigMap
    name: ci-images
    fieldPath: data.AISINIT_IMAGE
  targets:
    - select:
        kind: StatefulSet
        name: ais-proxy
      fieldPaths:
        - spec.template.spec.initContainers.[name=aisinit].image
- source:
    kind: ConfigMap
    name: proxy-vars
    fieldPath: data.NUM_PROXY
  targets:
    - select:
        kind: StatefulSet
        name: ais-proxy
      fieldPaths:
        - spec.replicas
- source:
    kind: ConfigMap
    name: target-vars
    fieldPath: data.NUM_TARGET
  targets:
    - select:
        kind: StatefulSet
        name: ais-proxy
      fieldPaths:
        - spec.template.spec.containers.[name=aisnode].args.3
      options:
        delimiter: "-ntargets="
        index: 1