apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/common

configMapGenerator:
- name: ais-cluster-config-override
  behavior: replace
  files:
    - ais_cluster_override.json

generatorOptions:
  disableNameSuffixHash: true